export const foods = [
  {
    id: '1',
    name: 'Manousheh',
    ingredients: 'Pizza Of Dubai',
    price: '8.30',
    image: require('../assets/banners/item1.jpg'),
  },
  {
    id: '2',
    name: 'Chelo Kebab',
    ingredients: 'A Heavenly Taste',
    price: '7.10',
    image: require('../assets/banners/item2.jpg'),
  },
  {
    id: '3',
    name: 'Al Harees',
    ingredients: 'Taste The Tradition',
    price: '5.10',
    image: require('../assets/banners/item3.jpg'),
  },
  {
    id: '4',
    name: 'Al Machboos',
    ingredients: 'Surprisingly Delicious',
    price: '9.55',
    image: require('../assets/banners/item4.jpg'),
  },
  {
    id: '5',
    name: 'Mandi',
    ingredients: 'A Rendezvous With Tradition',
    price: '9.55',
    image: require('../assets/banners/item5.jpg'),
  },
  {
    id: '6',
    name: 'Oozie',
    ingredients: 'Ramadan Special',
    price: '9.55',
    image: require('../assets/banners/item6.jpg'),
  },
  {
    id: '7',
    name: 'Tabbouleh',
    ingredients: 'For Those Who Are Health Conscious',
    price: '9.55',
    image: require('../assets/banners/item7.jpg'),
  },
];